services:
  app:
    image: raulbrennersc/devcontainer
    build: .
      
    volumes:
      - ../:/workspaces:cached

    devices: 
       - /dev/kvm:/dev/kvm 
      # Uncomment next line to enable debug using external mobile device (not working properly)
      #  - /dev/bus/usb:/dev/bus/usb

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: host

    