services:
  devcontainer:
    image: raulbrennersc/devcontainer:latest
    build:
      # dockerfile: Dockerfile
      context: .
      args:
        USERNAME: ${USER}
      
    volumes:
      - ../:/workspaces:cached

    devices: 
      # Needs "X11Forwarding yes" on /etc/ssh/sshd_config and "systemctl start sshd"
       - /dev/kvm:/dev/kvm 
      # Uncomment next line to enable debug using external mobile device (not working properly)
      #  - /dev/bus/usb:/dev/bus/usb

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: host

    