services:
  devcontainer:
    image: raulbrennersc/devcontainer:latest
    build:
      # dockerfile: Dockerfile
      context: .
      args:
        USERNAME: ${USER}
      
    volumes:
      # Needs "systemctl start sshd"
      - ../:/workspaces:cached
      - /tmp/.X-11-unix:/tmp/.X11-unix
    privileged: true
    group_add:
      - plugdev

    # devices: 
      # Uncomment next line to enable debug using external mobile device (not working properly)
      #  - /dev/bus/usb:/dev/bus/usb

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: host

    